### ISSUE TITLE
Change how start date is set for copied notifications

### ISSUE THREAD

**Issue by aarenson** [IUREDCap/auto-notify-module#1]
Recommendation: When a notification is created by copying it from another notification, set its start date to the date it was created, not the start date of the notification from which it was copied.

**Comment by mullen2** [comment]
@aarenson, thanks for the feedback. I wouldn't want to do this in general, because someone could create a notification with a start date in the future, and you could end up having a copy that has an earlier start date than the notification from which it was copied. Perhaps the start date should be set to the later of the current date and the start date of the copied notification.

What problem(s) do you see with how things are now?

**Comment by aarenson** [comment]
My newly created copy of a notification looks like it has been running longer than it has actually been running, which looks like an error to me. It hasn't prevented anything from happening, I just find it confusing.

Perhaps the new date should be the maximum of the old notification's date or the current date.

**Comment by mullen2** [comment]
This was fixed (I think in version 1.4.0).
